config/routes.rb
SassSite::Application.routes.draw do
  resources(:about, only: :index)
  resources(:contact, only: :create)
  resources(:home, only: :index)
  resources(:jobs, only: :index)
  resources(:our_work, only: :index, path: "our-work")
  resources(:services, only: :index)
  resources(:team, only: :index)

  root to: "home#index"

  # Contact
  get "contact" => "contact#index", :as => "contact"

  # Documents
  get "/bylaws", controller: :documents, to: "documents#bylaws", as: "bylaws"
  get "/code-of-conduct", controller: :markdown, to: "documents#code_of_conduct", as: "code_of_conduct"

  # Jobs
  get "/jobs/project-planner", controller: :jobs, to: 'jobs#project_planner', as: "project_planner"
  get "/jobs/rails-developer", controller: :jobs, to: 'jobs#rails_developer', as: "rails_developer"
  get "/jobs/product-planning-lead-2020", :to => redirect("/sassafras-product-planning-lead-2020.pdf")

  # Legacy link support
  get "/our_work" => redirect("/our-work")
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/views/about/index.html.erb
<div>
  <section>
    <h1 class="tagline">
      We are a growing <a href="http://techworker.coop">worker-owned technology cooperative</a> specializing in web/app design and development for social justice organizations, non-profits, academics, artists, and others.
    </h1>
  </section>

  <section>
    <div class="blurbs">
      <div class="blurb">
        <%= image_tag "leafBlue.png" %>
        <div>
          <h2>We deeply understand technology.</h2>
          <p>Bringing years of expertise from industry, academia, and social justice organizing, we understand the values that are embedded in code and design.</p>
        </div>
      </div>
      <div class="blurb">
        <%= image_tag "leafOrange.png" %>
        <div>
          <h2>We build for social change.</h2>
          <p>Inspired by the desire to promote social justice, we make beautiful, ethical, and easy to use technologies.</p>
        </div>
      </div>
    </div>
  </section>

  <section>
    <h1>We are passionate about our values</h1>
    <div>
      <p>We use our skills and expertise to promote values about which we care deeply.</p>
      <p>We work on a variety of projects. Some of our interests include projects that promote:</p>
      <ul>
        <li> sharing and solidarity economies</li>
        <li> participatory democracies </li>
        <li> healthful living </li>
        <li> environmental justice and sustainability </li>
        <li> ending oppression at the intersections of gender, race, class, sexuality, and ability </li>
        <li> community and individual empowerment </li>
      </ul>
    </div>
  </section>

  <section>
    <h1>We are a worker cooperative</h1>
    <p>
      Worker cooperatives, as defined by
      <%= link_to "The Tech Co-op Network", "http://techworker.coop/", target: "_blank" %>,
      are "businesses owned and democratically controlled by" their workers.
      As a democratically controlled business, we network with other like-minded
      groups. We are members of:
    </p>

    <div class="membership">
      <div class="blurb">
        <%= image_tag "usfwc.png" %>
        <div>
          <h4><%= link_to "The United States Federation of Worker Cooperatives", "http://usworker.coop/", target: "_blank" %></h4>
          <p>A network of democratically-owned businesses in the United States</p>
        </div>
      </div>
      <div class="blurb">
        <%= image_tag "tech-coop-network.png" %>
        <div>
          <h4><%= link_to "The Tech Co-op Network", "http://techworker.coop/", target: "_blank" %></h4>
          <p>A network of North American worker cooperatives focused on technology</p>
        </div>
      </div>
    </div>

    <!-- <p>As our logo reflects, we are based in Michigan helping to bring life back into our home.</p> -->
  </section>

  <section class="resources">
    <h1>Resources</h1>
    <ul>
      <li>
        <%= link_to "Bylaws of Sassafras Tech Collective", bylaws_path, target: "_blank" %>
      </li>
      <li>
        <%= link_to "Code of Conduct", code_of_conduct_path, target: "_blank" %>
      </li>
      <li>
      <%= link_to '"Anti-Oppressive Design"',
        "https://drive.google.com/file/d/0ByAb4A9TD5wBOHNRSGpNX3V5NTA/view",
        target: "_blank" %>
      by Tom Smyth and Jill Dimond
      </li>
    </ul>
  </section>

  <section class="credits">
    <h1>Credits</h1>
    <ul>
      <li>The blue and gray background art with the "Grow Together" text was created by
        <%= link_to "Pete Railand",
          "http://justseeds.org/artist/peterailand/", target: "_blank" %>
        of Justseeds Collective. Used with permission.
      </li>
    </ul>
  </section>
</div>